### ISSUE TITLE
After adding printer it does not appear in the sidebar until Switchboard closed & restarted

### ISSUE THREAD

**Issue by jeremypw** [elementary/switchboard-plug-printers#145]
## What Happened
I added a network printer with Switchboard/Printers using the '+' action on the sidebar.  Although a notification appeared on the desktop indicating a printer had been added, no new printer appeared in the sidebar.  After closing Switchboard and reopening it however, the new printer was listed.

## Expected Behavior
The new printer is listed and selected in the sidebar immediately after it has been successfully added.

## Platform Information

Elementary 6 daily

**Comment by selwynorren** [comment]
I have the same problem, after closing switchboard and opening it again, the printer then appears. I also see that removing a printer does not work at all (Network Printer)

**Comment by 4jNsY6fCVqZv** [comment]
Could this be solved in real time? Or would it make sense to inform users that some kind of app restart is necessary?

**Comment by selwynorren** [comment]
I am still having this issue with 6.1 Any changes to the printer and I have to close switchboard before the changes show up.

I am also struggling to delete phantom printers as well, not sure if this is all related
